### ISSUE TITLE
Too many triggers causes display errors

### ISSUE THREAD

**Issue by AavHRF** [Vleerian/FattKATT#3]
Per discussion in #the_outside_world, having too many triggers loaded into a trigger_list.txt file will cause some of them to not visually display on the list of triggers. This does not cause any wrong behavior in the triggering itself, it is simply a visual issue.
Screenshots provided by Thorn:
![](https://media.discordapp.net/attachments/934304852882907156/963609937739649044/unknown.png)
![](https://media.discordapp.net/attachments/934304852882907156/963609938020671498/unknown.png)

**Comment by Vleerian** [comment]
Addressed in Vleerian/FattKATT@b73a82c3c04e648b4a41fb12d49d137c660e1efd

Only the target FattKATT is currently waiting on will display a spinner
