### ISSUE TITLE
Exceeds API Rate Limit

### ISSUE THREAD

**Issue by EWSouls** [Vleerian/FattKATT#9]
### Subject of the issue
FattKATT can exceed NS API rate limit, result in user lockout.

### Your environment
1.3.2 on Windows from exe

### Steps to reproduce
Enter list of regions > 50 or so.

### Expected behaviour
LastUpdate should be rate limited to avoid lockout

### Actual behaviour
LastUpdate series of calls proceeds too fast and results in lockout if making more than 50ish requests. FattKATT then return errors, crashes, and will no restart (due to NS-side lockout).

**Comment by Vleerian** [comment]
This has been addressed in 1.3.3, and the upcoming 1.4
